In [10]:
import pandas as pd
import psycopg2

DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

In [11]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT 
    ROUND(AVG(salary_from)) AS avg_salary_from,
    ROUND(AVG(salary_to)) AS avg_salary_to
FROM vacancies
WHERE salary_from IS NOT NULL OR salary_to IS NOT NULL;
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\621595467.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   avg_salary_from  avg_salary_to
0          71065.0       110537.0

In [12]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT
    schedule,
    employment,
    COUNT(*) AS vacancy_count
FROM vacancies
group by 1, 2
order by 3 desc
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\3332937026.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

            schedule           employment  vacancy_count
0        Полный день     Полная занятость          35367
1   Удаленная работа     Полная занятость           7802
2      Гибкий график     Полная занятость           1593
3   Удаленная работа  Частичная занятость           1312
4     Сменный график     Полная занятость            940
5        Полный день           Стажировка            569
6     Вахтовый метод     Полная занятость            367
7        Полный день  Частичная занятость            347
8      Гибкий график  Частичная занятость            312
9        Полный день     Проектная работа            141
10  Удаленная работа     Проектная работа            133
11     Гибкий график           Стажировка            116
12    Сменный график  Частичная занятость            101
13  Удаленная работа           Стажировка             64
14     Гибкий график     Проектная работа             18
15    Сменный график           Стажировка             12
16    Вахтовый метод     Проектная работа              2
17    Сменный график     Проектная работа              1

In [13]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT
    experience,
    COUNT(*) AS Exp_required
from vacancies
group by 1
order by 2 desc
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\1023731795.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

           experience  exp_required
0  От 1 года до 3 лет         26152
1       От 3 до 6 лет         14511
2           Нет опыта          7197
3         Более 6 лет          1337

In [14]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)
query = """
SELECT
    e.name,
    COUNT(*) Count_vacancies_emp
from vacancies v
inner join employers e on v.employer_id = e.id
group by 1
order by 2 desc
limit 10
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\3737907202.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

                    name  count_vacancies_emp
0                 Яндекс                 1933
1             Ростелеком                  491
2               Тинькофф                  444
3                   СБЕР                  428
4          Газпром нефть                  331
5            ИК СИБИНТЕК                  327
6                    МТС                  292
7                DataArt                  247
8  Совкомбанк Технологии                  204
9             Первый Бит                  176

In [15]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query1 = """
SELECT
    a.name AS region_name,
    COUNT(DISTINCT e.id) AS employers_count,
    COUNT(v.id) AS vacancies_count
FROM areas a
LEFT JOIN employers e ON e.area = a.id
LEFT JOIN vacancies v ON v.area_id = a.id
where v.id is null
GROUP BY a.id, a.name
ORDER BY employers_count DESC
LIMIT 10
"""

df = pd.read_sql_query(query1, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\1273976886.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query1, connection)

             region_name  employers_count  vacancies_count
0                 Россия              410                0
1              Казахстан              207                0
2     Московская область               75                0
3     Краснодарский край               19                0
4               Беларусь               18                0
5     Ростовская область               18                0
6            Азербайджан               17                0
7  Нижегородская область               16                0
8   Республика Татарстан               16                0
9             Узбекистан               15                0

In [16]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT
    e.name emp_name,
    COUNT(distinct v.area_id) AS region_count
FROM employers e
INNER JOIN vacancies v ON v.employer_id = e.id
LEFT JOIN areas a ON a.id = v.area_id
GROUP BY e.id, 1
ORDER BY 2 DESC
LIMIT 10
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\189248407.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

                     emp_name  region_count
0                      Яндекс           181
1                  Ростелеком           152
2                  Спецремонт           116
3      Поляков Денис Иванович            88
4                   ООО ЕФИН             71
5                  Совкомбанк            63
6                         МТС            55
7  ЭФКО, Управляющая компания            49
8                Почта России            48
9                        КРОН            48

In [17]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT
    e.name,
    COUNT(ei.industry_id) industries_count
FROM employers e
left join employers_industries ei ON ei.employer_id = e.id
group by e.id, 1
having count(ei.industry_id) = 0
ORDER BY 1 DESC
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\1729616095.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

                                                   name  industries_count
0                               Яшнова Алена Викторовна                 0
1                                          Ярпож Казань                 0
2       Ярославский ЦГМС - филиал ФГБУ Центральное УГМС                 0
3                              Ярославский филиал ПГУПС                 0
4              Ярославский завод упаковочных материалов                 0
...                                                 ...               ...
8414                                        1221Системс                 0
8415                                           101 Плюс                 0
8416                                          100 печей                 0
8417                                          1001 Soft                 0
8418  1000 мелочей (ИП Гафиатуллина Гульшат Митарисо...                 0

[8419 rows x 2 columns]

In [18]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT
    e.name
FROM employers e
INNER JOIN employers_industries ei ON ei.employer_id = e.id
GROUP BY e.id, e.name
HAVING COUNT(DISTINCT ei.industry_id) = 4
ORDER BY e.name
"""
df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\1047913668.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

                 name
0        101 Интернет
1            21vek.by
2                2ГИС
3                  2К
4         4 пикселя +
...               ...
1133            ЮРИОН
1134  ЮТИП Технологии
1135           ЯКласс
1136            ЯрНео
1137    Яшин&Партнёры

[1138 rows x 1 columns]

In [19]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """

WITH filtered_data AS (
    SELECT 
        a.name AS region_name,
        v.id AS vac_id
    FROM employers e
    INNER JOIN vacancies v ON v.employer_id = e.id
    INNER JOIN areas a ON a.id = v.area_id
    WHERE e.name = 'Яндекс'
        AND a.name IN ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 
                       'Казань', 'Нижний Новгород', 'Челябинск', 'Самара', 
                       'Омск', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 
                       'Пермь', 'Воронеж', 'Волгоград', 'Краснодар')
),

COMBINED AS (

    SELECT 
        region_name,
        COUNT(vac_id) AS vac_count
    FROM filtered_data
    GROUP BY region_name

    UNION ALL

    SELECT 
        'Total' AS region_name,
        COUNT(vac_id) AS vac_count
    FROM filtered_data
    
            )
            
SELECT
    region_name,
    vac_count,
    CASE WHEN region_name = 'Total' THEN 1 ELSE 0 END
FROM COMBINED
ORDER BY
    vac_count DESC;
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\4068037806.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

        region_name  vac_count  case
0             Total        485     1
1            Москва         54     0
2   Санкт-Петербург         42     0
3      Екатеринбург         39     0
4   Нижний Новгород         36     0
5       Новосибирск         35     0
6           Воронеж         32     0
7         Краснодар         30     0
8               Уфа         26     0
9            Самара         26     0
10   Ростов-на-Дону         25     0
11            Пермь         25     0
12           Казань         25     0
13        Волгоград         24     0
14       Красноярск         23     0
15        Челябинск         22     0
16             Омск         21     0

In [29]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """

WITH filtered_data AS
(
    SELECT
        a.name AS region_name,
        v.id AS vac_id
    FROM employers e
    INNER JOIN vacancies v ON v.employer_id = e.id
    INNER JOIN areas a ON a.id = v.area_id
    WHERE e.name = 'Яндекс'
        AND a.name IN ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург',
                       'Казань', 'Нижний Новгород', 'Челябинск', 'Самара',
                       'Омск', 'Ростов-на-Дону', 'Уфа', 'Красноярск',
                       'Пермь', 'Воронеж', 'Волгоград', 'Краснодар')
)

SELECT
    COALESCE(region_name, 'Total') AS region_name,
    COUNT(vac_id) AS vac_count
FROM filtered_data
GROUP BY ROLLUP(region_name)
ORDER BY
    region_name = 'Total' DESC,
    vac_count asc
"""
df = pd.read_sql_query(query, connection)
df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\2016134805.py:35: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

        region_name  vac_count
0             Total        485
1              Омск         21
2         Челябинск         22
3        Красноярск         23
4         Волгоград         24
5             Пермь         25
6            Казань         25
7    Ростов-на-Дону         25
8            Самара         26
9               Уфа         26
10        Краснодар         30
11          Воронеж         32
12      Новосибирск         35
13  Нижний Новгород         36
14     Екатеринбург         39
15  Санкт-Петербург         42
16           Москва         54

In [30]:
query = """

SELECT
    COALESCE(a.name, 'Total') AS region_name,
    COUNT(*) AS vac_count
FROM employers e
JOIN vacancies v ON v.employer_id = e.id
JOIN areas a ON a.id = v.area_id
WHERE e.name = 'Яндекс'
        AND a.name IN ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург',
                       'Казань', 'Нижний Новгород', 'Челябинск', 'Самара',
                       'Омск', 'Ростов-на-Дону', 'Уфа', 'Красноярск',
                       'Пермь', 'Воронеж', 'Волгоград', 'Краснодар')

GROUP BY ROLLUP(a.name)
ORDER BY
    COALESCE(a.name, 'Total') = 'Total' DESC,
    COUNT(*) ASC
    
"""

df = pd.read_sql_query(query, connection)
df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\3659147781.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

        region_name  vac_count
0             Total        485
1              Омск         21
2         Челябинск         22
3        Красноярск         23
4         Волгоград         24
5             Пермь         25
6            Казань         25
7    Ростов-на-Дону         25
8            Самара         26
9               Уфа         26
10        Краснодар         30
11          Воронеж         32
12      Новосибирск         35
13  Нижний Новгород         36
14     Екатеринбург         39
15  Санкт-Петербург         42
16           Москва         54

In [22]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT 
    COUNT(*) AS vacancies_with_employer
FROM vacancies
WHERE LOWER(name) LIKE '%data%' 
   OR name ILIKE '%данн%'
"""
df = pd.read_sql_query(query, connection)
df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\789728741.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   vacancies_with_employer
0                     1771

In [23]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT COUNT(*) AS junior_data_scientist_vacancies
FROM vacancies v
WHERE (
    LOWER(v.name) LIKE '%data scientist%'
    OR LOWER(v.name) LIKE '%data science%'
    OR v.name ILIKE '%исследователь данных%'
    OR (
        LOWER(v.name) LIKE '%ml%' 
        AND LOWER(v.name) NOT LIKE '%html%'  -- исключаем HTML
    )
    OR LOWER(v.name) LIKE '%machine learning%'
    OR v.name ILIKE '%машинн%обучен%'
)
AND (
    LOWER(v.name) LIKE '%junior%'
    OR v.experience = 'Нет опыта'
    OR v.experience = 'Стажировка'
);
"""
df = pd.read_sql_query(query, connection)
df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\173141412.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   junior_data_scientist_vacancies
0                               51

In [24]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT COUNT(DISTINCT v.id) AS ds_vacancies_with_sql
FROM vacancies v
WHERE (
    -- Условия для дата-сайентиста (как в предыдущем задании, но без Junior)
    LOWER(v.name) LIKE '%data scientist%'
    OR LOWER(v.name) LIKE '%data science%'
    OR v.name ILIKE '%исследователь данных%'
    OR (
        LOWER(v.name) LIKE '%ml%' 
        AND LOWER(v.name) NOT LIKE '%html%'
    )
    OR LOWER(v.name) LIKE '%machine learning%'
    OR v.name ILIKE '%машинн%обучен%'
)
AND (
    LOWER(v.key_skills) LIKE '%sql%'
    OR LOWER(v.key_skills) LIKE '%postgres%'
    OR LOWER(v.key_skills) LIKE '%postgre%'
    OR LOWER(v.key_skills) LIKE '%pgsql%'
);
"""
df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\2354913659.py:31: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   ds_vacancies_with_sql
0                    229

In [25]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT COUNT(DISTINCT v.id) AS ds_vacancies_with_python
FROM vacancies v
WHERE (
    -- Условия для дата-сайентиста
    LOWER(v.name) LIKE '%data scientist%'
    OR LOWER(v.name) LIKE '%data science%'
    OR v.name ILIKE '%исследователь данных%'
    OR (
        LOWER(v.name) LIKE '%ml%' 
        AND LOWER(v.name) NOT LIKE '%html%'
    )
    OR LOWER(v.name) LIKE '%machine learning%'
    OR v.name ILIKE '%машинн%обучен%'
)
AND (
    LOWER(v.key_skills) LIKE '%python%'
);
"""
df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\3030839151.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   ds_vacancies_with_python
0                       357

In [26]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
SELECT ROUND(AVG(skill_count), 2) AS avg_skills_per_vacancy
FROM (
    SELECT 
        v.id,
        LENGTH(v.key_skills) - LENGTH(REPLACE(v.key_skills, CHR(9), '')) + 1 AS skill_count
    FROM vacancies v
    WHERE (
        LOWER(v.name) LIKE '%data scientist%'
        OR LOWER(v.name) LIKE '%data science%'
        OR v.name ILIKE '%исследователь данных%'
        OR (LOWER(v.name) LIKE '%ml%' AND LOWER(v.name) NOT LIKE '%html%')
        OR LOWER(v.name) LIKE '%machine learning%'
        OR v.name ILIKE '%машинн%обучен%'
    )
    AND v.key_skills IS NOT NULL
    AND v.key_skills != ''
) AS vacancy_skills;
"""

df = pd.read_sql_query(query, connection)

df

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\1648176318.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

   avg_skills_per_vacancy
0                    6.55

In [27]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """
WITH ds_vacancies AS (
    SELECT 
        CASE 
            WHEN salary_from IS NOT NULL AND salary_to IS NOT NULL 
                THEN (salary_from + salary_to) / 2.0
            WHEN salary_from IS NOT NULL 
                THEN salary_from
            WHEN salary_to IS NOT NULL 
                THEN salary_to
        END AS calculated_salary,
        experience
    FROM vacancies
    WHERE (
        LOWER(name) LIKE '%data scientist%'
        OR LOWER(name) LIKE '%data science%'
        OR name ILIKE '%исследователь данных%'
        OR (LOWER(name) LIKE '%ml%' AND LOWER(name) NOT LIKE '%html%')
        OR LOWER(name) LIKE '%machine learning%'
        OR name ILIKE '%машинн%обучен%'
    )
    AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
)
SELECT 
    ROUND(AVG(calculated_salary)) AS avg_salary_3_6_years
FROM ds_vacancies
WHERE experience = 'От 3 до 6 лет'
  AND calculated_salary IS NOT NULL;
"""
df = pd.read_sql_query(query, connection)
print(df)

   avg_salary_3_6_years
0              256454.0

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\2939901330.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

In [34]:
connection = psycopg2.connect(
   dbname=DBNAME,
   user=USER,
   host=HOST,
   password=PASSWORD,
   port=PORT
)

query = """

SELECT
    experience as exp,
    ROUND(AVG(
            COALESCE(
                (salary_from + salary_to) / 2, salary_from, salary_to)), 0) AS avg_ds
FROM vacancies
WHERE

(
    name ILIKE '%data scientist%'
    OR name ILIKE '%data science%'
    OR name ILIKE '%исследователь данных%'
    OR(name LIKE '%ML%' AND name NOT LIKE '%HTML%')
    OR name ILIKE '%machine learning%'
    OR name ILIKE '%машинн%обучен%'

)

AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)

GROUP BY experience

"""
df = pd.read_sql_query(query, connection)
print(df)

                  exp    avg_ds
0           Нет опыта   74643.0
1  От 1 года до 3 лет  139675.0
2       От 3 до 6 лет  243115.0

C:\Users\nulaa\AppData\Local\Temp\ipykernel_11248\3253524975.py:34: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)